name: Angular Compile
on:
  pull_request:
    branches:
      - master
      - develop
  push:
    branches:
      - master

env:
  node-version: "14.x"
defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache-node
        with:
         path: node_modules
         key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
         restore-keys: ${{ runner.os }}-node-
      - name: Setup Node ${{ env.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - name: Install node packages
        if: steps.cache-node.outputs.cache-hit != 'true'
        run: |
          yarn install
      - name: LINT - Detect Console Logs or Debugger
        run: |
          yarn run lint
      - name: BUILD - Compile Check
        run: |
          yarn run build
