name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build
          rm -rf node_modules
          rm -rf src

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.FTPS_SERVER }}
          username: ${{ secrets.FTPS_USER }}
          password: ${{ secrets.FTPS_PASSWORD }}
          protocol: ftps
          port: 21
          security: loose
          local-dir: ./dist/delgaudiomike/
