name: Build and Deploy
on:
  push:
    branches:
      - develop
      - master
  pull_request:
    branches:
      - develop

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.3.2

      - name: Use Node 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: 🔨 Build Project
        run: |
          npm install
          npm run build

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@beta-v4
        with:
          server: ${{ secrets.FTPS_SERVER }}
          username: ${{ secrets.FTPS_USER }}
          password: ${{ secrets.FTPS_PASSWORD }}
          protocol: ftps
          port: 21
          security: loose
          local-dir: ./dist/delgaudiomike/
